language: objective-c
osx_image: xcode9

script:
  - set -o pipefail
  - xcodebuild test -enableCodeCoverage YES -workspace Viscosity.xcodeproj -scheme Viscosity -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0' ONLY_ACTIVE_ARCH=NO | xcpretty

